@extends('admin.layouts.master')

@section('title', 'Available Epins')

@section('page-css')
    <!-- Internal DataTables css-->
	<link href="{{ asset('assets/plugins/datatable/dataTables.bootstrap4.min.css') }}" rel="stylesheet" />
	<link href="{{ asset('assets/plugins/datatable/responsivebootstrap4.min.css') }}" rel="stylesheet" />
@endsection

@section('content')

    <!-- Page Header -->
    <div class="page-header">
        <div>
            <h2 class="main-content-title tx-24 mg-b-5">Available Epins</h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ asset('/admin/dashboard') }}">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">Epins</li>
            </ol>
        </div>
    </div>
    <!-- End Page Header -->

    <!-- Row -->
    <div class="row row-sm">
        <div class="col-12">
            <div class="card custom-card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-6">
                            <h6 class="main-content-label mb-1">Available Epins</h6>
                        </div>
                        <div class="col-6 d-flex flex-row-reverse">
                            <button class="btn btn-danger my-2 btn-icon-text delete-pins" style="opacity:0" id="delete-btn" onclick="bulkDeletePins()">
                                <i class="fe fe-trash-2 mr-2"></i> Delete
                            </button>
                        </div>
                    </div>
                    <div class="table-responsive mt-4 ">
                        <table id="dataTable" class="table w-100 border-t0 text-nowrap text-nowrap table-bordered text-center">
                            <thead>
                                <tr>
                                    <th>
                                        <label class="ckbox">
                                            <input type="checkbox" id="selectAll">
                                            <span></span>
                                        </label>
                                    </th>
                                    <th> #</th>
                                    <th>Created At</th>
                                    <th>Epin Code</th>
                                    <th>Amount</th>
                                    <th>Issued To</th>
                                    <th>Generated By</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Row -->

@endsection

@section('page-js')
    <!-- Internal Data Table js -->
    <script src="{{ asset('assets/plugins/datatable/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/datatable/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/datatable/dataTables.responsive.min.js') }}"></script>
    <!-- <script src="https://cdn.datatables.net/buttons/2.1.0/js/dataTables.buttons.min.js"></script> -->
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        $(document).ready(function(){

            var selected_pins = [];

            $("#selectAll").click(function(){
                $("input[type=checkbox]").prop('checked', $(this).prop('checked'));
                
                if($(this).prop('checked')){
                    $('.pin_id:checked').each(function(){
                        selected_pins.push($(this).val());
                    });
                }else{
                    //$("input[type=checkbox]").prop('checked', $(this).prop('checked'));
                    selected_pins = [];
                }

                showHideDeleteBtn();
            });
            
            $(document).on('click', '.pin_id', function(){

                if($(this).prop("checked") == true){
                    selected_pins.push($(this).val());
                }else{
                    selected_pins.splice(selected_pins.indexOf($(this).val()), 1);
                }

                showHideDeleteBtn();

            });

            function showHideDeleteBtn(){
                if(selected_pins.length > 0){
                    $('#delete-btn').css("opacity", 1);
                }else{
                    $('#delete-btn').css("opacity", 0);
                }
            }

            $(document).on('click', '.delete-pins', function(e){
                e.preventDefault();
                Swal.fire({
                    text: 'Do you want to delete selected E-pins?',
                    showCancelButton: true,
                    icon: 'error',
                    confirmButtonText: 'Yes Delete!',
                }).then((result) => {
                    if (result.isConfirmed) {

                        // $('.pin_id:checked').each(function(){
                        //     id.push($(this).val());
                        // });

                        if(selected_pins.length > 0)
                        {

                            $.ajax({
                                url:"{{ route('admin.epins.destroy') }}",
                                method:'post',
                                data:{ selected_pins, _token: "{{ csrf_token() }}" },
                                dataType:'json',
                                success:function(data)
                                {
                                    Swal.fire({
                                        text: data.message,
                                        icon: 'success',
                                        timer: 1500,
                                        showConfirmButton: false,
                                    });
                                    $('#dataTable').DataTable().ajax.reload();
                                },
                                error: function(xhr, textStatus, errorThrown) {
                                    Swal.fire({
                                        text: 'Something went wrong! Please try again.',
                                        icon: 'error',
                                        showConfirmButton: true,
                                    }).then( (result) => {
                                        if (result.value) {
                                            window.location.reload();
                                        }
                                    });
                                }
                            });

                        }else{
                            Swal.fire({
                                text: 'No E-pins selected!',
                                icon: 'error',
                                showConfirmButton: true,
                            });
                        }

                    } 
                })

            });

            $("#dataTable").DataTable({
                // dom: 'Bfrtip',
                // buttons: [
                //     {
                //         text: 'My button',
                //         className: 'btn btn-danger btn-sm delete-pins',
                //         action: function ( e, dt, node, config ) {
                //             //alert( 'Button activated' );
                //             bulkDeletePins()
                //         }
                //     },
                //     'pageLength'
                // ],
                language:{
                    searchPlaceholder:"Search...",
                    sSearch:"",
                    lengthMenu:"_MENU_ items/page"
                },
                pageLength: 100,
                processing: true,
                serverSide: true,
                ajax: {
                    url: "{{ route('admin.epins.available') }}",
                    type: 'post',
                    data: function (data) {
                        data._token = "{{ csrf_token() }}";
                    }
                },
                columns: [
                    {data: 'checkbox', orderable:false, searchable:false},
                    {data: 'DT_RowIndex', name: 'DT_RowIndex', searchable: false},
                    {data: 'createdDate', name: 'createdDate'},
                    {data: 'epin_code', name: 'epin_code'},
                    {data: 'amount', name: 'amount'},
                    {data: 'issued_to', name: 'issued_to'},
                    {data: 'user.name', name: 'generated_by'},
                ]
            })
        });
    </script>
@endsection